
export function agendaEmail({
  hostName,
  agendaPreview,
  editorUrl
}: {
  hostName: string;
  agendaPreview: string;
  editorUrl: string;
}) {
  return `
    <html>
      <body style="font-family:Arial,sans-serif;line-height:1.4;">
        <h2 style="margin-bottom:8px;">🎉 Your Teho.ai agenda is ready</h2>
        <p>Hi ${hostName || "there"},<br>
        We turned your invite into a focused, time‑boxed agenda. Click below to review & tweak:</p>
        <p style="text-align:center;margin:24px 0">
          <a href="${editorUrl}"
             style="background:#1f2937;color:#fff;padding:12px 20px;border-radius:6px;text-decoration:none;">
             Open & Edit Agenda
          </a>
        </p>
        <pre style="background:#f5f5f5;padding:12px;border-radius:6px;">${agendaPreview}</pre>
        <hr>
        <small style="color:#888;">Generated by Teho.ai — add agenda@teho.ai to any invite and save prep time.</small>
      </body>
    </html>
  `;
}
