export function agendaEmail({
  hostName,
  agendaPreview,
  editorUrl,
  blueprintPreview = null
}: {
  hostName: string;
  agendaPreview: string;
  editorUrl: string;
  blueprintPreview?: {
    title: string;
    totalDuration: string;
    steps: Array<{name: string; duration: string; description: string}>;
    materials: string[];
  } | null;
}) {
  // Create a simpler, markdown-style preview format
  let blueprintPreviewText = '';
  
  if (blueprintPreview) {
    blueprintPreviewText = `
## ${blueprintPreview.title}
**Total Duration:** ${blueprintPreview.totalDuration} minutes

### Agenda Preview:
${blueprintPreview.steps && blueprintPreview.steps.length > 0 
  ? blueprintPreview.steps.map((step, index) => 
      `${index + 1}. **${step.name}** (${step.duration} min)\n   ${step.description?.substring(0, 100)}${step.description?.length > 100 ? '...' : ''}`
    ).join('\n\n') + (blueprintPreview.steps.length > 2 ? '\n\n...and more' : '')
  : 'No agenda items yet'}

### Materials Needed:
${blueprintPreview.materials && blueprintPreview.materials.length > 0
  ? blueprintPreview.materials.map(material => `• ${material}`).join('\n') + 
    (blueprintPreview.materials.length > 3 ? '\n• ...and more' : '')
  : 'No materials specified'}
`;
  }

  return `
    <html>
      <body style="font-family:Arial,sans-serif;line-height:1.4;">
        <div style="max-width:600px;margin:0 auto;padding:20px;background-color:#ffffff;border-radius:8px;">
          <h2 style="margin-bottom:15px;color:#1f2937;">🎉 Your Teho.ai agenda is ready</h2>
          
          <p style="margin-bottom:20px;">Hi ${hostName || "there"},<br>
          We turned your calendar invite into a focused, time‑boxed agenda using Teho.ai. Click below to review & tweak:</p>
          
          <div style="text-align:center;margin:30px 0;">
            <a href="${editorUrl}"
               style="background:#1f2937;color:#fff;padding:14px 24px;border-radius:6px;text-decoration:none;font-weight:bold;display:inline-block;">
               Open & Edit Agenda
            </a>
          </div>
          
          ${blueprintPreview ? `
          <div style="background:#f9f9f9;padding:20px;border-radius:6px;margin:20px 0;border-left:4px solid #1f2937;">
            <pre style="white-space:pre-wrap;margin:0;font-family:inherit;font-size:14px;line-height:1.5;">${blueprintPreviewText}</pre>
          </div>
          ` : ''}
          
          <div style="background:#f5f5f5;padding:15px;border-radius:6px;margin:20px 0;">
            <strong>Original Meeting Description:</strong>
            <pre style="white-space:pre-wrap;margin-top:10px;font-family:inherit;">${agendaPreview}</pre>
          </div>
          
          <div style="margin-top:30px;padding-top:15px;border-top:1px solid #eee;">
            <p style="font-size:12px;color:#888;margin:0;">
              <strong>Workshop link:</strong> <a href="${editorUrl}" style="color:#4F46E5;">${editorUrl}</a>
            </p>
            <p style="font-size:12px;color:#888;margin-top:10px;">
              Generated by <a href="https://teho.ai" style="color:#4F46E5;">Teho.ai</a> — add agenda@teho.ai to any invite and save prep time.
            </p>
          </div>
        </div>
      </body>
    </html>
  `;
}
