
export function agendaEmail({
  hostName,
  agendaPreview,
  editorUrl,
  blueprintPreview = null
}: {
  hostName: string;
  agendaPreview: string;
  editorUrl: string;
  blueprintPreview?: {
    title: string;
    totalDuration: string;
    steps: Array<{name: string; duration: string; description: string}>;
    materials: string[];
  } | null;
}) {
  // Create a simpler, markdown-style preview format
  let blueprintPreviewText = '';
  
  if (blueprintPreview) {
    blueprintPreviewText = `
## ${blueprintPreview.title}
**Total Duration:** ${blueprintPreview.totalDuration} minutes

### Agenda Preview:
${blueprintPreview.steps && blueprintPreview.steps.length > 0 
  ? blueprintPreview.steps.map((step, index) => 
      `${index + 1}. **${step.name}** (${step.duration} min)\n   ${step.description?.substring(0, 100)}${step.description?.length > 100 ? '...' : ''}`
    ).join('\n\n') + (blueprintPreview.steps.length > 2 ? '\n\n...and more' : '')
  : 'No agenda items yet'}

### Materials Needed:
${blueprintPreview.materials && blueprintPreview.materials.length > 0
  ? blueprintPreview.materials.map(material => `• ${material}`).join('\n') + 
    (blueprintPreview.materials.length > 3 ? '\n• ...and more' : '')
  : 'No materials specified'}
`;
  }

  return `
    <html>
      <body style="font-family:Arial,sans-serif;line-height:1.4;">
        <div style="max-width:600px;margin:0 auto;padding:20px;background-color:#ffffff;border-radius:8px;">
          <h2 style="margin-bottom:15px;color:#1f2937;">🎉 Your Teho.ai agenda is ready</h2>
          
          <p style="margin-bottom:20px;">Hi ${hostName || "there"},<br>
          We turned your calendar invite into a focused, time‑boxed agenda using Teho.ai. Click below to review & tweak:</p>
          
          <div style="text-align:center;margin:30px 0;">
            <a href="${editorUrl}"
               style="background:#1f2937;color:#fff;padding:14px 24px;border-radius:6px;text-decoration:none;font-weight:bold;display:inline-block;">
               Open & Edit Agenda
            </a>
          </div>
          
          ${blueprintPreview ? `
          <div style="background:#f9f9f9;padding:20px;border-radius:6px;margin:20px 0;border-left:4px solid #1f2937;">
            <pre style="white-space:pre-wrap;margin:0;font-family:inherit;font-size:14px;line-height:1.5;">${blueprintPreviewText}</pre>
          </div>
          ` : ''}
          
          <div style="background:#f5f5f5;padding:15px;border-radius:6px;margin:20px 0;">
            <strong>Original Meeting Description:</strong>
            <pre style="white-space:pre-wrap;margin-top:10px;font-family:inherit;">${agendaPreview}</pre>
          </div>
          
          <div style="margin-top:30px;padding-top:15px;border-top:1px solid #eee;">
            <p style="font-size:12px;color:#888;margin:0;">
              <strong>Workshop link:</strong> <a href="${editorUrl}" style="color:#4F46E5;">${editorUrl}</a>
            </p>
            <p style="font-size:12px;color:#888;margin-top:10px;">
              Generated by <a href="https://teho.ai" style="color:#4F46E5;">Teho.ai</a> — add agenda@teho.ai to any invite and save prep time.
            </p>
          </div>
        </div>
      </body>
    </html>
  `;
}

import { Resend } from "npm:resend@3.1.0";

export async function sendBlueprintReadyEmail(
  resend: Resend,
  to: string,
  workshopTitle: string,
  workshopDescription: string,
  blueprintShareUrl: string
): Promise<void> {
  const subject = `✨ Your AI-Generated Blueprint for "${workshopTitle}" is Ready!`;
  const siteUrl = Deno.env.get('SITE_URL') || 'https://app.teho.ai';
  const logoUrl = `${siteUrl}/logo-teho-dark.svg`; // Assuming a dark logo variant for light email backgrounds

  // Make sure we're using the /workshop route instead of /blueprint/:shareId
  const workshopUrl = blueprintShareUrl.includes('/blueprint/') 
    ? blueprintShareUrl.replace('/blueprint/', '/workshop?id=')
    : blueprintShareUrl;

  const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${subject}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 0; background-color: #f4f4f7; color: #333333; }
        .container { width: 100%; max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
        .header { padding: 30px 20px 20px 20px; text-align: center; border-bottom: 1px solid #eeeeee; }
        .header img { height: 40px; width: auto; }
        .content { padding: 30px 40px; }
        .content h1 { font-size: 24px; font-weight: bold; color: #2c3e50; margin-top: 0; margin-bottom: 15px; }
        .content p { font-size: 16px; line-height: 1.6; margin-bottom: 10px; }
        .description-box { background-color: #f9f9f9; padding: 15px; border-radius: 6px; margin-bottom: 25px; border-left: 3px solid #3498db; }
        .description-box p { font-size: 15px; line-height: 1.5; margin:0; }
        .button-container { text-align: center; margin-bottom: 25px; }
        .button { background-color: #3498db; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block; font-size: 16px; }
        .footer { padding: 20px 40px; text-align: center; border-top: 1px solid #eeeeee; background-color: #f8f9fa; }
        .footer p { font-size: 12px; color: #7f8c8d; margin: 0; }
        .footer a { color: #3498db; text-decoration: none; }
        .footer code { background-color: #ecf0f1; padding: 2px 4px; border-radius: 3px; color: #2c3e50; }
      </style>
    </head>
    <body>
      <table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color: #f4f4f7;">
        <tr>
          <td align="center" style="padding: 20px;">
            <div class="container">
              <div class="header">
                <img src="${logoUrl}" alt="teho.ai Logo">
              </div>
              <div class="content">
                <h1>Your Blueprint is Ready!</h1>
                <p>Hi there,</p>
                <p>
                  Great news! We've used AI to generate a blueprint for your meeting: <strong>${workshopTitle}</strong>.
                </p>
                <div class="description-box">
                  <p>${workshopDescription}</p>
                </div>
                <div class="button-container">
                  <a href="${workshopUrl}" target="_blank" class="button">
                    View & Share Blueprint
                  </a>
                </div>
                <p>
                  You can share this link with attendees or collaborators to give them a clear overview of the plan.
                </p>
              </div>
              <div class="footer">
                <p>Powered by <a href="https://teho.ai" target="_blank">teho.ai</a></p>
                <p style="margin-top: 5px;">
                  Automate your meeting preparation. Add <code>agenda@teho.ai</code> to your next calendar invite.
                </p>
              </div>
            </div>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `;

  try {
    await resend.emails.send({
      from: "Teho Meeting Assistant <meeting@teho.ai>", // More professional from address
      to,
      subject,
      html: htmlContent,
      // Adding email headers to improve deliverability
      headers: {
        "X-Entity-Ref-ID": `blueprint-${Date.now()}`, // Unique ID to prevent threading
        "List-Unsubscribe": "<mailto:unsubscribe@teho.ai>", // Required by many inbox providers
      },
      // Including text version improves deliverability
      text: `Your Blueprint is Ready!
      
Great news! We've used AI to generate a blueprint for your meeting: "${workshopTitle}"

${workshopDescription}

View & Share Your Blueprint: ${workshopUrl}

You can share this link with attendees or collaborators to give them a clear overview of the plan.

Powered by teho.ai
Automate your meeting preparation. Add agenda@teho.ai to your next calendar invite.`,
    });
    console.log(`Blueprint ready email successfully sent to ${to}`);
  } catch (error) {
    console.error(`Error sending blueprint ready email to ${to}:`, error);
    throw error;
  }
}
