
import { Resend } from "npm:resend@3.1.0";
import type { Blueprint } from "../types/workshop.ts"; // Ensure Blueprint type is imported

/**
 * Email template for agenda confirmation email
 */
function agendaEmail({
  hostName,
  agendaPreview, // This is the original meeting description
  editorUrl, // This will now be the blueprintShareUrl
  blueprintPreview = null
}: {
  hostName: string;
  agendaPreview: string;
  editorUrl: string; // Renamed for consistency, but represents blueprintShareUrl
  blueprintPreview?: {
    title: string;
    totalDuration: string | number;
    steps: Array<{name: string; duration: string | number; description: string}>;
    materials: string[];
  } | null;
}) {
  // Create a simpler, markdown-style preview format
  let blueprintPreviewText = '';
  
  if (blueprintPreview) {
    blueprintPreviewText = `
## ${blueprintPreview.title}
**Total Duration:** ${blueprintPreview.totalDuration} minutes

### Agenda Preview:
${blueprintPreview.steps && blueprintPreview.steps.length > 0 
  ? blueprintPreview.steps.map((step, index) => 
      `${index + 1}. **${step.name}** (${step.duration} min)\n   ${step.description?.substring(0, 100)}${step.description?.length > 100 ? '...' : ''}`
    ).join('\n\n') + (blueprintPreview.steps.length > 2 ? '\n\n...and more' : '')
  : 'No agenda items yet'}

### Materials Needed:
${blueprintPreview.materials && blueprintPreview.materials.length > 0
  ? blueprintPreview.materials.map(material => `• ${material}`).join('\n') + 
    (blueprintPreview.materials.length > 3 ? '\n• ...and more' : '')
  : 'No materials specified'}
`;
  }

  return `
    <html>
      <body style="font-family:Arial,sans-serif;line-height:1.4;">
        <div style="max-width:600px;margin:0 auto;padding:20px;background-color:#ffffff;border-radius:8px;">
          <h2 style="margin-bottom:15px;color:#1f2937;">🎉 Your Teho.ai Blueprint is Ready!</h2>
          
          <p style="margin-bottom:20px;">Hi ${hostName || "there"},<br>
          We've transformed your calendar invite into a structured workshop blueprint using Teho.ai. Click the link below to view and share it:</p>
          
          <div style="text-align:center;margin:30px 0;">
            <a href="${editorUrl}"
               style="background:#1f2937;color:#fff;padding:14px 24px;border-radius:6px;text-decoration:none;font-weight:bold;display:inline-block;">
               View Your Blueprint
            </a>
          </div>
          
          ${blueprintPreview ? `
          <div style="background:#f9f9f9;padding:20px;border-radius:6px;margin:20px 0;border-left:4px solid #1f2937;">
            <pre style="white-space:pre-wrap;margin:0;font-family:inherit;font-size:14px;line-height:1.5;">${blueprintPreviewText}</pre>
          </div>
          ` : ''}
          
          <div style="background:#f5f5f5;padding:15px;border-radius:6px;margin:20px 0;">
            <strong>Original Meeting Invitation:</strong>
            <pre style="white-space:pre-wrap;margin-top:10px;font-family:inherit;">${agendaPreview}</pre>
          </div>
          
          <div style="margin-top:30px;padding-top:15px;border-top:1px solid #eee;">
            <p style="font-size:12px;color:#888;margin:0;">
              <strong>Blueprint link:</strong> <a href="${editorUrl}" style="color:#4F46E5;">${editorUrl}</a>
            </p>
            <p style="font-size:12px;color:#888;margin-top:10px;">
              Generated by <a href="https://teho.ai" style="color:#4F46E5;">Teho.ai</a> — add agenda@teho.ai to any invite to generate a blueprint.
            </p>
          </div>
        </div>
      </body>
    </html>
  `;
}

/**
 * Send a confirmation email to the workshop organizer with a link to the generated blueprint
 */
export async function sendConfirmationEmail(
  resend: Resend,
  email: string,
  eventSummary: string, // Original event summary
  eventDescription: string, // Original event description
  blueprintShareUrl: string, // Changed from workshopUrl
  blueprint: Blueprint | null // The generated blueprint
): Promise<void> {
  try {
    // Format the blueprint preview for the email
    const blueprintPreview = blueprint ? {
      title: blueprint.title || eventSummary, // Fallback to event summary if blueprint title is missing
      totalDuration: blueprint.totalDuration,
      steps: blueprint.steps ? blueprint.steps.slice(0, 3) : [], // Get first 3 steps only, ensure steps exist
      materials: blueprint.materials || [] // Ensure materials exist
    } : null;

    console.log("Blueprint Share URL:", blueprintShareUrl);
    console.log("Original event description length:", eventDescription.length);
    console.log("Blueprint for email preview available:", !!blueprintPreview);
    console.log("Preparing to send blueprint confirmation email to:", email);

    // Send the email
    const { data, error } = await resend.emails.send({
      from: "Teho.ai Blueprint Assistant <agenda@teho.ai>", // Updated sender name
      to: email,
      subject: `Your Teho.ai Blueprint: ${eventSummary}`, // Updated subject
      html: agendaEmail({
        hostName: email.split('@')[0],
        agendaPreview: eventDescription, // Original meeting description
        editorUrl: blueprintShareUrl,    // Link to view the blueprint
        blueprintPreview                 // The structured preview of the blueprint
      })
    });

    console.log("Email send result:", JSON.stringify({ data, error }));

    if (error) {
      throw error;
    }

    console.log("Blueprint confirmation email sent to:", email);
  } catch (error) {
    console.error("Failed to send blueprint confirmation email:", error);
    throw new Error(`Failed to send blueprint confirmation email: ${error.message}`);
  }
}

